[package]
name = "zing"
version = "0.1.0"
authors = ["Jeronimo <33876901+Xinovaz@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crow = "0.7.2"
rand = "0.8.5"